# Generated by Django 2.2.1 on 2019-05-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190521_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='blog_id',
        ),
    ]
